title = "RankStore"  # From Git
gitRepoUrl = "https://github.com/123marble/RankStore" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
# favicon = ""

# From git:
organizationName = "123marble"
projectName = "RankStore"
url = "https://123marble.github.io"
baseUrl = "/RankStore"
tagline = "Ranked Datastore"

[footer]
style = "dark"
copyright = "Copyright © 2021 AuthorName. Built with Moonwave and Docusaurus"