name: Docs

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i -g moonwave@latest
      - name: Publish
        run: |
          moonwave build --publish
